apiVersion: v1
kind: Service
metadata:
  labels:
    app: satisfactory-dedicated-server
  name: satisfactory-dedicated-server
  namespace: satisfactory-dedicated-server
spec:
  ports:
  - name: query
    port: 15777
    protocol: UDP
    targetPort: 15777
  - name: beacon
    port: 15000
    protocol: UDP
    targetPort: 15000
  - name: game
    port: 7777
    protocol: UDP
    targetPort: 7777
  selector:
    app: satisfactory-dedicated-server
  type: LoadBalancer
  loadBalancerIP: 10.0.0.245