#
# File: ./.github/workflows/release.yml
#
name: Release Docker Version
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+-e"
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+-erc[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Setup Go in order to vendor dependencies in a later setp.
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Parse Repo Name
        id: parse_repo_name
        run: |
          echo ::set-output name=repo_name::"$( echo '${{ github.repository }}' | awk -F '/' '{print tolower($2)}' )"
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile_exp
          push: true
          platforms: linux/amd64
          labels: ${{ steps.release.outputs.labels }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.parse_repo_name.outputs.repo_name }}:${{ github.ref_name }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.parse_repo_name.outputs.repo_name }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.parse_repo_name.outputs.repo_name }}:buildcache,mode=max
